title: Jared Henriques
email: 'hey@jared.is'
description: 'Hey, I’m Jared. I enjoy solving problems with others'
baseurl: '/blog'
url: 'https://jared.is/' # The base hostname & protocol for your site
twitter: 'https://twitter.com/jaredhenriques'
linkedin: 'https://www.linkedin.com/in/jaredhenriques/'

markdown:  kramdown
permalink: pretty
paginate:  60

sass:
  style: compressed

gems:
  - jekyll-paginate

include:
  - _pages

exclude:
  - node_modules
  - README.md
  - LICENSE.md
  - vendor
  - Gemfile
  - Gemfile.lock

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
